### ISSUE TITLE
How can uninstall dotfiles?

### ISSUE THREAD

**Issue by eofferma** [fatso83/dotfiles#11]
Please help me, how can I recover my old files, for example  ~/.zsh?

**Comment by eofferma** [comment]
Nevermind, I didn't find any backup process on the setup. I made a Newbie error. That is the way that We learn sometimes 😅

**Comment by fatso83** [comment]
Sorry to hear you lost work, but I made this for my own use, open-sourcing as inspiration for your own setups, so trying to support a general backup routine will probably not be something I will spend time supporting :-)
