### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by cganterh** [fatso83/dotfiles#12]

**Comment by fatso83** [comment]
It says in the second paragraph of the README :) 
![image](https://user-images.githubusercontent.com/618076/197147091-ef55863d-7b7d-4461-ae6b-8836e5093630.png)

It's just meant to share utility scripts and serve as inspiration for a simple approach to sharing configs. So feel free: fork and remove whatever you do not need or care for.

P.S. [Your website](http://cganterh.net) is down.
