### ISSUE TITLE
Commnt for **inotify-consumers**

### ISSUE THREAD

**Issue by Hannes-III** [fatso83/dotfiles#22]
Thank you for `inotify-consumers`.
I was very interested in how it works and so I looked into the code.

I have a remark to the line 65:
```
echo "$INOTIFY" | cut -d "/" -s --output-delimiter=" "   -f 3,5 | sed -e 's/:.*//'| uniq |awk '{print $1}' |uniq -c
                                                                                    ^^^^
```
using `uniq` in that way you require that all the lines you get from grepping through the proc files are sorted, which I would not count on. Better pipe through `sort` before?

Looking @ your code I discovered the `cut` command. I have never used it before, `awk` was my tool, thank you.

Using `awk` for years, i would change your line to:
```
echo "$INOTIFY" | awk -F'[/:]' '{if(! pidr[$3][$5]){ pid[$3]++;pidr[$3][$5]=1}} END{ for(i in pid) {print " " pid[i] " " i}} '
```
there is only one pipe into one process.

**Comment by Hannes-III** [comment]
I just found out, that I commented on an old version of `inotify-consumers`.
I close this right away.
Sorry.

**Comment by fatso83** [comment]
No worries! Thanks for reviewing 🤓
