### ISSUE TITLE
Thousands separators for `inotify-consumers`

### ISSUE THREAD

**Issue by lonix1** [fatso83/dotfiles#7]
First off, thanks for creating the `inotify-consumers` script, it's incredibly useful!

How would I go about printing large numbers with thousands separators? (For the count and pid columns, and the totals row.)

**Comment by fatso83** [comment]
I use the standard POSIX printf function, so you can just change the LC_NUMERIC to your wanted locale. 

See https://unix.stackexchange.com/a/113798/18594

```
LC_NUMERIC=en_US printf "%'.f\n" 123456789
123,456,789
```

You probably also need to change the %d specifier to use the floating point format specifier, %f, like in the example. Not sure if the integer specifier (%d) supports formatting like that. 

https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers#L70

**Comment by lonix1** [comment]
That's very helpful, I'll look into it, thanks!

I'm going to try make it a command line switch, e.g. `inotify-consumers --thousands` or something like that, I'll post it here if I succeed.

**Comment by fatso83** [comment]
@lonix1 it should suffice to just change the format specifier without hardcoding the locale when using your switch. 

That way the grouping will be correct according to the local locale rules (as US grouping rules differ from Norwegian grouping rules).

**Comment by lonix1** [comment]
I tried to get it to work with locales, like this:
````sh
LC_NUMERIC=en_US inotify-consumers --thousands
````

But both `%f` and `%d` ignored it and just printed thousands separators. Oh well, in my case it's what I want anyway!

For anyone who wants it, here are the two `printf` [lines to change](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers#L69-L72):
````sh
                 printf "%'$(( WLEN - 2 ))d  %s\n" "$CNT" "$(grep -e "^\ *${PID}\ " <<< "$PSLIST")"
#                         ^
                 TOT=$(( TOT + CNT ))
             done
             printf "\n%'$(( WLEN - 2 ))d  %s\n" "$TOT" "WATCHES TOTAL COUNT"
#                       ^
````

Notice:
- I kept the `%d`, and just added an apostrophe before both of them
- I didn't add a `--thousands` switch because I want it to show that way always by default

Thanks @fatso83 for this cool script. Maybe some day we can add locales to it, but unsure how. My edits are good enough for now.

(Also if I have time I'll try rewrite the printing bits using `column`.)

**Comment by fatso83** [comment]
You have _per definition_ added locale support. See [the manual for `printf`](https://man7.org/linux/man-pages/man3/printf.3.html) under _Flag characters_:
>        '      For decimal conversion (i, d, u, f, F, g, G) the output is
>              to be grouped with thousands' grouping characters if the
>              locale information indicates any.  (See setlocale(3).)

And it works just as advertised:
```
$ LC_NUMERIC=C printf "%'d\n" 1234
1234

$ LC_NUMERIC=en_US.utf8 printf "%'d\n" 1234
1,234

$ LC_NUMERIC=nb_NO.utf8 printf "%'d\n" 1234
1 234
```

So you can just have that as the default and setting `C` (POSIX) as the locale will remove the grouping.

**Comment by lonix1** [comment]
Makes more sense now, thanks :smile:
